INSERT INTO `praca_grupowa`.`books` (
  `author`,
  `available_copies`,
  `cover_url`,
  `genre`,
  `published_year`,
  `title`,
  `total_copies`
) VALUES
  ('George Orwell', 5, NULL, 'Dystopian', 1949, '1984', 5),
  ('Aldous Huxley', 4, NULL, 'Dystopian', 1932, 'Brave New World', 5),
  ('J.R.R. Tolkien', 7, NULL, 'Fantasy', 1937, 'The Hobbit', 7),
  ('J.K. Rowling', 6, NULL, 'Fantasy', 1997, 'Harry Potter and the Sorcerer''s Stone', 6),
  ('F. Scott Fitzgerald', 5, NULL, 'Fiction', 1925, 'The Great Gatsby', 5),
  ('Harper Lee', 4, NULL, 'Fiction', 1960, 'To Kill a Mockingbird', 5),
  ('Jane Austen', 3, NULL, 'Romance', 1813, 'Pride and Prejudice', 4),
  ('J.D. Salinger', 4, NULL, 'Fiction', 1951, 'The Catcher in the Rye', 5),
  ('J.R.R. Tolkien', 6, NULL, 'Fantasy', 1954, 'The Lord of the Rings', 6),
  ('Ray Bradbury', 4, NULL, 'Dystopian', 1953, 'Fahrenheit 451', 5),
  ('Dan Brown', 5, NULL, 'Thriller', 2003, 'The Da Vinci Code', 5),
  ('Paulo Coelho', 3, NULL, 'Fiction', 1988, 'The Alchemist', 4),
  ('Stieg Larsson', 5, NULL, 'Mystery', 2005, 'The Girl with the Dragon Tattoo', 5),
  ('Gillian Flynn', 4, NULL, 'Thriller', 2012, 'Gone Girl', 5),
  ('Suzanne Collins', 5, NULL, 'Dystopian', 2008, 'The Hunger Games', 5),
  ('John Green', 4, NULL, 'Young Adult', 2012, 'The Fault in Our Stars', 5),
  ('C.S. Lewis', 6, NULL, 'Fantasy', 1950, 'The Chronicles of Narnia', 6),
  ('Stephen Hawking', 3, NULL, 'Science', 1988, 'A Brief History of Time', 4),
  ('Cormac McCarthy', 2, NULL, 'Post-Apocalyptic', 2006, 'The Road', 3),
  ('Stephen King', 5, NULL, 'Horror', 1977, 'The Shining', 5),
  ('Margaret Atwood', 4, NULL, 'Dystopian', 1985, 'The Handmaid''s Tale', 5),
  ('Khaled Hosseini', 3, NULL, 'Fiction', 2003, 'The Kite Runner', 4),
  ('Markus Zusak', 4, NULL, 'Historical Fiction', 2005, 'The Book Thief', 5),
  ('Daniel Kahneman', 3, NULL, 'Psychology', 2011, 'Thinking, Fast and Slow', 4),
  ('Yuval Noah Harari', 5, NULL, 'History', 2011, 'Sapiens: A Brief History of Humankind', 5),
  ('Tara Westover', 3, NULL, 'Memoir', 2018, 'Educated', 4),
  ('Michelle Obama', 4, NULL, 'Memoir', 2018, 'Becoming', 5),
  ('Mark Manson', 3, NULL, 'Self-Help', 2016, 'The Subtle Art of Not Giving a F*ck', 4),
  ('James Clear', 5, NULL, 'Self-Help', 2018, 'Atomic Habits', 5),
  ('Paula Hawkins', 4, NULL, 'Thriller', 2015, 'The Girl on the Train', 5),
  ('Frank Herbert', 5, NULL, 'Sci-Fi', 1965, 'Dune', 5),
  ('Orson Scott Card', 3, NULL, 'Sci-Fi', 1985, 'Ender''s Game', 4),
  ('William Gibson', 4, NULL, 'Sci-Fi', 1984, 'Neuromancer', 5),
  ('Douglas Adams', 5, NULL, 'Sci-Fi', 1979, 'The Hitchhiker''s Guide to the Galaxy', 5),
  ('Bram Stoker', 3, NULL, 'Horror', 1897, 'Dracula', 4),
  ('Mary Shelley', 4, NULL, 'Horror', 1818, 'Frankenstein', 5),
  ('Victor Hugo', 2, NULL, 'Historical Fiction', 1862, 'Les Misérables', 3),
  ('Leo Tolstoy', 3, NULL, 'Historical Fiction', 1869, 'War and Peace', 4),
  ('Fyodor Dostoevsky', 4, NULL, 'Fiction', 1866, 'Crime and Punishment', 5),
  ('Homer', 2, NULL, 'Epic Poetry', -800, 'The Odyssey', 3),
  ('Homer', 2, NULL, 'Epic Poetry', -800, 'The Iliad', 3),
  ('Dante Alighieri', 3, NULL, 'Poetry', 1320, 'The Divine Comedy', 4),
  ('Herman Melville', 4, NULL, 'Fiction', 1851, 'Moby-Dick', 5),
  ('Charlotte Brontë', 3, NULL, 'Fiction', 1847, 'Jane Eyre', 4),
  ('Emily Brontë', 4, NULL, 'Fiction', 1847, 'Wuthering Heights', 5),
  ('Oscar Wilde', 3, NULL, 'Fiction', 1890, 'The Picture of Dorian Gray', 4),
  ('Arthur Golden', 4, NULL, 'Historical Fiction', 1997, 'Memoirs of a Geisha', 5),
  ('Tracy Chevalier', 3, NULL, 'Historical Fiction', 1999, 'The Girl with the Pearl Earring', 4),
  ('Yann Martel', 4, NULL, 'Fiction', 2001, 'Life of Pi', 5),
  ('Thomas Harris', 3, NULL, 'Thriller', 1988, 'The Silence of the Lambs', 4),
  ('Andy Weir', 4, NULL, 'Sci-Fi', 2011, 'The Martian', 5),
  ('Ernest Cline', 3, NULL, 'Sci-Fi', 2011, 'Ready Player One', 4),
  ('Stephen King', 4, NULL, 'Horror', 1978, 'The Stand', 5),
  ('Stephen King', 3, NULL, 'Horror', 1986, 'It', 4),
  ('Kathryn Stockett', 4, NULL, 'Historical Fiction', 2009, 'The Help', 5),
  ('Stieg Larsson', 3, NULL, 'Mystery', 2006, 'The Girl Who Played with Fire', 4),
  ('Stieg Larsson', 3, NULL, 'Mystery', 2007, 'The Girl Who Kicked the Hornets'' Nest', 4),
  ('E.L. James', 4, NULL, 'Romance', 2011, 'Fifty Shades of Grey', 5),
  ('Jojo Moyes', 3, NULL, 'Romance', 2012, 'Me Before You', 4),
  ('Diana Gabaldon', 4, NULL, 'Historical Fiction/Romance', 1991, 'Outlander', 5),
  ('Suzanne Collins', 5, NULL, 'Dystopian', 2009, 'The Hunger Games: Catching Fire', 5),
  ('Suzanne Collins', 4, NULL, 'Dystopian', 2010, 'The Hunger Games: Mockingjay', 5),
  ('C.S. Lewis', 3, NULL, 'Fantasy', 1950, 'The Lion, the Witch and the Wardrobe', 4),
  ('E.B. White', 3, NULL, 'Children''s', 1952, 'Charlotte''s Web', 4),
  ('Maurice Sendak', 3, NULL, 'Children''s', 1963, 'Where the Wild Things Are', 4),
  ('Dr. Seuss', 3, NULL, 'Children''s', 1957, 'The Cat in the Hat', 4),
  ('Dr. Seuss', 3, NULL, 'Children''s', 1960, 'Green Eggs and Ham', 4),
  ('Margaret Wise Brown', 2, NULL, 'Children''s', 1947, 'Goodnight Moon', 3),
  ('Eric Carle', 3, NULL, 'Children''s', 1969, 'The Very Hungry Caterpillar', 4),
  ('Dr. Seuss', 3, NULL, 'Children''s', 1990, 'Oh, the Places You''ll Go!', 4),
  ('Bill Martin Jr.', 2, NULL, 'Children''s', 1967, 'Brown Bear, Brown Bear, What Do You See?', 3),
  ('A.A. Milne', 3, NULL, 'Children''s', 1926, 'Winnie-the-Pooh', 4),
  ('J.K. Rowling', 5, NULL, 'Fantasy', 1998, 'Harry Potter and the Chamber of Secrets', 5),
  ('J.K. Rowling', 4, NULL, 'Fantasy', 1999, 'Harry Potter and the Prisoner of Azkaban', 5),
  ('J.K. Rowling', 5, NULL, 'Fantasy', 2000, 'Harry Potter and the Goblet of Fire', 5),
  ('J.K. Rowling', 4, NULL, 'Fantasy', 2003, 'Harry Potter and the Order of the Phoenix', 5),
  ('J.K. Rowling', 4, NULL, 'Fantasy', 2005, 'Harry Potter and the Half-Blood Prince', 5),
  ('J.K. Rowling', 5, NULL, 'Fantasy', 2007, 'Harry Potter and the Deathly Hallows', 5),
  ('George R.R. Martin', 4, NULL, 'Fantasy', 1996, 'A Game of Thrones', 5),
  ('George R.R. Martin', 4, NULL, 'Fantasy', 1998, 'A Clash of Kings', 5),
  ('George R.R. Martin', 5, NULL, 'Fantasy', 2000, 'A Storm of Swords', 5),
  ('George R.R. Martin', 3, NULL, 'Fantasy', 2005, 'A Feast for Crows', 4),
  ('George R.R. Martin', 4, NULL, 'Fantasy', 2011, 'A Dance with Dragons', 5),
  ('Abi Daré', 3, NULL, 'Fiction', 2020, 'The Girl with the Louding Voice', 4),
  ('Sally Rooney', 3, NULL, 'Fiction', 2018, 'Normal People', 4),
  ('Madeline Miller', 4, NULL, 'Fantasy', 2018, 'Circe', 5),
  ('Alex Michaelides', 3, NULL, 'Thriller', 2019, 'The Silent Patient', 4),
  ('Delia Owens', 4, NULL, 'Fiction', 2018, 'Where the Crawdads Sing', 5),
  ('Celeste Ng', 3, NULL, 'Fiction', 2017, 'Little Fires Everywhere', 4),
  ('Margaret Atwood', 4, NULL, 'Dystopian', 2019, 'The Testaments', 5),
  ('Andy Weir', 4, NULL, 'Sci-Fi', 2021, 'Project Hail Mary', 5),
  ('Matt Haig', 3, NULL, 'Fiction', 2020, 'The Midnight Library', 4),
  ('Brit Bennett', 4, NULL, 'Fiction', 2020, 'The Vanishing Half', 5),
  ('V.E. Schwab', 4, NULL, 'Fantasy', 2020, 'The Invisible Life of Addie LaRue', 5),
  ('Ashley Audrain', 3, NULL, 'Thriller', 2021, 'The Push', 4),
  ('Kazuo Ishiguro', 4, NULL, 'Sci-Fi', 2021, 'Klara and the Sun', 5);
